### ISSUE TITLE
Add text editor option?

### ISSUE THREAD

**Issue by dajare** [b-t-k/b-t-k.github.io#1]
Hi! This "meta-guide" was a real help to me when I started my SE productions. I've now done six, and I think you're reviewing my current project. :)

I had a couple suggestions for your Guide, so thought I'd log them here.

First is just a [suggestion about text editors][1]. As you note, the Guide is orientated towards MacOS; perhaps it's worth adding [VS Codium][2] to your list. It's just a "libre" version of Visual Studio Code ... but that has real advantages. It is very much cross-platform (Windows, MacOS, and Linuxes all supported), and a huge user base. ALL the things BBedit does, VS Codium does too. (I've used BB, too. It's lovely, but just for Macs.)

Obviously very minor! But thought I'd mention it.

[1]: https://github.com/b-t-k/b-t-k.github.io/blob/main/a-guide/part-1.md#bbedit--text-editors
[2]: https://vscodium.com/

**Comment by b-t-k** [comment]
Thanks. I've incorporated you suggestions. I will have to check VS Codium out. I've let this guide languish as it didn't manage to attract any of my editor friends but I really need to get it finished off one of these days :-)
